window.GUILD_CONFIG={
 discordUrl:"",
 timezone:"America/Chicago",
 guild:{master:"Deydriane"},
 events:{
  raid:{day:"Sunday",time:"19:00",enabled:true},
  expedition:{day:"Sunday",time:"19:00",enabled:true}
 }
};