const c=window.GUILD_CONFIG||{};const sb=window.supabase?.createClient(c.supabase.url,c.supabase.publishableKey);const $=id=>document.getElementById(id);
const authPanel=$("authPanel"),accountPanel=$("accountPanel"),signupForm=$("signupForm"),loginForm=$("loginForm");
function status(id,msg,type=""){const x=$(id);x.className="formStatus"+(type?" "+type:"");x.textContent=msg}
function showSignup(){signupForm.hidden=false;loginForm.hidden=true;$("showSignup").classList.add("active");$("showLogin").classList.remove("active")}
function showLogin(){signupForm.hidden=true;loginForm.hidden=false;$("showLogin").classList.add("active");$("showSignup").classList.remove("active")}
$("showSignup").onclick=showSignup;$("showLogin").onclick=showLogin;
signupForm.onsubmit=async e=>{e.preventDefault();const username=$("username").value.trim(),email=$("email").value.trim().toLowerCase(),password=$("password").value,character=$("character").value.trim(),discord=$("discord").value.trim();status("signupStatus","CREATING YOUR ACCOUNT…");const {error}=await sb.auth.signUp({email,password,options:{data:{username,character_name:character,discord_id:discord}}});if(error){status("signupStatus",error.message,"error");return}status("signupStatus","ACCOUNT CREATED. CHECK YOUR EMAIL TO CONFIRM YOUR ACCOUNT. YOU START AS A RECRUIT AND YOUR CHARACTER IS PENDING APPROVAL.","success");signupForm.reset()};
loginForm.onsubmit=async e=>{e.preventDefault();status("loginStatus","LOGGING IN…");const {error}=await sb.auth.signInWithPassword({email:$("loginEmail").value.trim().toLowerCase(),password:$("loginPassword").value});if(error){status("loginStatus",error.message,"error");return}await boot()};
async function boot(){const {data:{user}}=await sb.auth.getUser();if(!user){authPanel.hidden=false;accountPanel.hidden=true;return}const {data:profile}=await sb.from("profiles").select("username,role").eq("id",user.id).maybeSingle();if(!profile){status("loginStatus","ACCOUNT PROFILE IS STILL INITIALIZING. TRY AGAIN IN A MOMENT.","error");return}authPanel.hidden=true;accountPanel.hidden=false;$("accountUsername").textContent=(profile.username||"MEMBER").toUpperCase()+".";$("accountRole").textContent="CURRENT ACCESS: "+profile.role.replace("_"," ").toUpperCase()+".";$("accountCharacter").textContent="Your character signup is private and pending leadership approval. Once approved, it is visible to Officers and above."}
$("accountLogout").onclick=async()=>{await sb.auth.signOut();boot()};sb.auth.onAuthStateChange(()=>boot());boot();